# Generated by Django 4.0.5 on 2022-07-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('trading_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('site_features', models.CharField(max_length=300)),
            ],
        ),
    ]
